title: Michael Pearce Bayes Opt Blog
description: > # this means to ignore newlines until "baseurl:"
  I like working on machine learning models with optimization and here 
  is a collection my research projects.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http:/bayesianblog.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Michael Pearce # add your name
author-img: Pics/con_LEVI_REVI_NREVI-crop-2.png # add your photo
about-author: Researcher and avid cyclist # add description
social-twitter: MichaelLeopoldP # add your Twitter handle
social-github: scrambledpie  # add your Github handle
social-linkedin: michael-pearce-3a8b18b6 # add your Linkedin handle
social-email: scrambledpie@gmail.com # add your Email address

# Disqus
# discus-identifier: mr-bddrown # add your discus identifier

# Tracker
# analytics: # Google Analylltics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
